# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale pull requests

on:
  schedule:
  - cron: '*/1 * * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Get open PRs using GitHub Script
        id: get_prs
        uses: actions/github-script@v5
        with:
          script: |
            const oneDayAgo = new Date(new Date().setDate(new Date().getDate() - 1));
            const prs = await github.rest.pulls.list({
              owner: 'sowmyav27',
              repo: 'github-actions',
              state: 'open'
            });
            const stalePRs = prs.data.filter(pr => new Date(pr.created_at) < oneDayAgo).map(pr => `- ${pr.title} (#${pr.number}): ${pr.html_url}`).join('\n');
            return stalePRs;
          result-encoding: string

      - name: Notify on Slack if stale PRs exist
        if: steps.get_prs.outputs.result
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Open PRs for more than 1 day:\n${{ steps.get_prs.outputs.result }}"}' ${{ secrets.SLACK_WEBHOOK_URL }}
