name: Shepherd Mark stale pull requests

on:
  schedule:
  - cron: '0 0 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    steps:      
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Check PRs and compile report
        id: compile_report
        uses: actions/github-script@v5
        with:
          script: |
            const fiveDaysAgo = new Date(new Date().setDate(new Date().getDate() - 5)); 
            const threeDaysAgo = new Date(new Date().setDate(new Date().getDate() - 3));
            let report = '';
            let noReviewsReport = '';
            let noChangesReport = '';
            let awaitingReview = '';
            let needsChanges = '';
            let needsMerge = '';

            // Fetch open PRs
            const prs = await github.paginate(github.rest.pulls.list, {
              owner: 'rancher',
              repo: 'shepherd',
              state: 'open',
              per_page: 100,
            });

            for (const pr of prs) {
              
              const createdDate = new Date(pr.created_at); 
              const updatedDate = new Date(pr.updated_at); 

              // Fetch PR reviews
              const reviews = await github.rest.pulls.listReviews({
                owner: 'rancher',
                repo: 'shepherd',
                pull_number: pr.number,
                per_page: 100,
              });
              let lastReviewDate = null
              let changesRequested = ""
              let numberOfApprovedState = 0
              
              // No reviews on the PR for > 5 days
              if (reviews.data.length == 0 && createdDate < fiveDaysAgo) {
                noReviewsReport += `#${pr.number} ${pr.html_url}\n`;
              } 
              else {
                  for (const review of reviews.data) {
                    const reviewDate = new Date(review.submitted_at);
                    if(!lastReviewDate || reviewDate > lastReviewDate) {
                      lastReviewDate = reviewDate
                      changesRequested = review.state
                      if ( review.state === "APPROVED"){
                        numberOfApprovedState+=1
                      }
                  }
                }
              }
              if ( updatedDate < fiveDaysAgo && (changesRequested === "OPEN" || numberOfApprovedState === 1) ){
                noChangesReport += `#${pr.title} (#${pr.number}) ${pr.html_url}\n`;
              }
              if (lastReviewDate && (changesRequested === "CHANGES_REQUESTED" || numberOfApprovedState === 1) && (lastReviewDate < threeDaysAgo && updatedDate > lastReviewDate)) {
                awaitingReview += `#${pr.title} (#${pr.number}) ${pr.html_url}\n`;
              }
              if (lastReviewDate && (changesRequested === "CHANGES_REQUESTED" || numberOfApprovedState === 1) && (lastReviewDate < threeDaysAgo && updatedDate <= lastReviewDate)) {
                needsChanges += `#${pr.title} (#${pr.number}) ${pr.html_url}\n`;
              }
              if (lastReviewDate && numberOfApprovedState >=2 && (lastReviewDate < threeDaysAgo)) {
                needsMerge += `#${pr.title} (#${pr.number}) ${pr.html_url}\n`;
              }
            }
            report += `Stale PR with no review (more than 5 days): \n` + noReviewsReport +`\n`
              + `No changes in this PR for over 5 days: \n`+ noChangesReport +`\n` 
              + `Changes made but awaiting review (more than 3 days since last update): \n`+ awaitingReview +`\n` 
              + `PR with requested changes and no updates (more than 3 days): \n`+ needsChanges +`\n`
              + `Reviewed but not merged (more than 3 days since review): \n` + needsMerge
            
            return report;
           
          result-encoding: string

      - name: Notify on Slack 
        if: steps.compile_report.outputs.result
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"PR Report:\n${{ steps.compile_report.outputs.result }}"}' ${{ secrets.SLACK_WEBHOOK_URL }}
