name: Shepherd Mark stale pull requests

on:
  schedule:
  - cron: '* * * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    steps:      
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Check PRs and compile report
        id: compile_report
        uses: actions/github-script@v5
        with:
          script: |
            const fiveDaysAgo = new Date(new Date().setDate(new Date().getDate() - 5)); 
            const threeDaysAgo = new Date(new Date().setDate(new Date().getDate() - 3));
            let report = '';
            let noReviewsReport = '';
            let noChangesReport = '';
            let needsReviews = '';
            let needsChanges = '';
            let needsMerge = '';

            // Fetch open PRs
            const prs = await github.paginate(github.rest.pulls.list, {
              owner: 'rancher',
              repo: 'shepherd',
              state: 'open',
              per_page: 100,
            });

            for (const pr of prs) {
              
              const createdDate = new Date(pr.created_at); 
              const updatedDate = new Date(pr.updated_at); 

              // Fetch PR reviews
              const reviews = await github.rest.pulls.listReviews({
                owner: 'rancher',
                repo: 'shepherd',
                pull_number: pr.number,
                per_page: 100,
              });
              let lastReviewDate = null
              let lastReviewStateOne = ""
              let lastReviewStateTwo = ""
              let numberOfApprovedState = 0
              statesCompare = ["COMMENTED", "CHANGES_REQUESTED"]
              
              // No reviews on the PR for > 5 days
              if (reviews.data.length == 0 && createdDate < fiveDaysAgo) {
                noReviewsReport += `${pr.title} #${pr.number} ${pr.html_url} ${pr.author}\n`;
              } 
              else {
                  for (const review of reviews.data) {
                    const reviewDate = new Date(review.submitted_at);
                    if(!lastReviewDate || reviewDate > lastReviewDate) {
                      lastReviewDate = reviewDate
                      lastReviewStateTwo = lastReviewStateOne
                      lastReviewStateOne = review.state
                      if ( review.state === "APPROVED"){
                        numberOfApprovedState+=1
                      }
                  }
                }
              }
              //no updates for more than 3 days
              if (lastReviewDate && (lastReviewDate < threeDaysAgo && updatedDate <= lastReviewDate) && statesCompare.includes(lastReviewStateOne) && statesCompare.includes(lastReviewStateTwo)) {
                needsChanges += `${pr.title} (#${pr.number}) ${pr.html_url} ${pr.author} \n`;
                
              } else if (lastReviewDate && (updatedDate > lastReviewDate) && (updatedDate < threeDaysAgo)){
                //Reviews needed
                needsReviews += `${pr.title} (#${pr.number}) ${pr.html_url} ${pr.author} \n`;

              }  else if (lastReviewDate && numberOfApprovedState >=2 && (lastReviewDate < threeDaysAgo) && !statesCompare.includes(lastReviewStateOne)) {
                needsMerge += `${pr.title} (#${pr.number}) ${pr.html_url} ${pr.author} \n`;
              }
            }
            report += `PRs with no reviews yet: \n` + noReviewsReport +`\n`
              + `PRs that need reviews: \n`+ needsReviews +`\n` 
              + `PRs with changes requested: \n`+ needsChanges +`\n`
              + `PRs that need to be merged: \n` + needsMerge
            
            return report;
           
          result-encoding: string

      - name: Notify on Slack 
        if: steps.compile_report.outputs.result
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"PR Report:\n${{ steps.compile_report.outputs.result }}"}' ${{ secrets.SLACK_WEBHOOK_URL }}
