name: Notify on Failure

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false  # Ensures all tests run, even if one fails
      matrix:
        test-suite: [Test1, Test2, Test3, Test4]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Run test - ${{ matrix.test-suite }}
        id: run-test
        run: |
          echo "Running ${{ matrix.test-suite }}..."
          if [ "${{ matrix.test-suite }}" != "Test3" ]; then  # let's pretend Test3 passes
            echo "${{ matrix.test-suite }}" >> failed-tests.txt
            exit 1
          fi

      - name: Upload failure file
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: failed-tests-${{ matrix.test-suite }}
          path: failed-tests.txt

  report-failures:
    needs: test
    runs-on: ubuntu-latest
    if: always()  # Run even if previous jobs fail
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        
      - name: Download all failure artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Combine failed test list
        run: |
          mkdir -p combined
          find artifacts -name 'failed-tests-*' -exec echo {} \; >> combined/failed.txt
          failed=$(cat combined/failed.txt | xargs | sed 's|.*/failed-tests-||' | tr ' ' ', ')
          echo "FAILED_TESTS=$failed" >> $GITHUB_ENV

      - name: Notify Slack
        uses: ./.github/actions/my-action  # assuming this is your composite action location
        with:
          test_results: "Status of test cases run"
          run_id: ${{ github.run_id }}
          run_number: ${{ github.run_number }}
          status: "failure"
          source_repo: ${{ github.repository }}
          failed_tests: ${{ env.FAILED_TESTS }}
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL_CI_TESTS_ALERTS }}
    # steps:
    #   - name: Collect and aggregate failures
    #     run: |
    #       FAILED_TESTS=""
    #       for test in ${{ needs.test.outputs.failed_tests }}; do
    #         if [[ -n "$test" ]]; then
    #           FAILED_TESTS+="$test\n"
    #         fi
    #       done
    #       echo "FAILED_TESTS=$FAILED_TESTS" >> $GITHUB_ENV  # Use GITHUB_ENV for subsequent steps

    #   - name: Debug Failure Collection
    #     run: echo "Collected Failures Sowmya ${{ env.FAILED_TESTS }}"  # Print out the collected failures
 
    #   - name: Report Failures to Slack
    #     if: always()
    #     uses: sowmyav27/github-actions/.github/actions/my-action@main
    #     with:
    #       test_results: "${{ env.FAILED_TESTS }}"
    #       run_id: ${{ github.run_id }}
    #       run_number: ${{ github.run_number }}
    #       status: failure
    #       source_repo: ${{ github.repository }}
    #       webhook_url: ${{ secrets.SLACK_WEBHOOK_URL_CI_TESTS_ALERTS }}
