name: Notify on Failure

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false  # Ensures all tests run, even if one fails
      matrix:
        test-suite: [Test1, Test2, Test3, Test4]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Run test - ${{ matrix.test-suite }}
        id: run-test
        run: |
          echo "Running ${{ matrix.test-suite }}..."
          if [ "${{ matrix.test-suite }}" != "Test3" ]; then
            echo "${{ matrix.test-suite }}" >> failed-tests.txt
            exit 1
          fi

      - name: Upload failure file
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: failed-tests-${{ matrix.test-suite }}
          path: failed-tests.txt

  report-test-results:
    needs: test
    runs-on: ubuntu-latest
    if: always()  # Run even if previous jobs fail
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        
      - name: Download all failure artifacts
        if: needs.test.result == 'failure'
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Combine failed test list
        if: needs.test.result == 'failure'
        run: |
          mkdir -p combined
          find artifacts -name 'failed-tests-*' -exec echo {} \; >> combined/failed.txt
          echo "FAILED_TESTS=$(find artifacts -name 'failed-tests-*' -exec basename {} \; | sed 's/failed-tests-//'|  paste -sd ' ' -)" >> $GITHUB_ENV

      - name: Notify Slack
        uses: ./.github/actions/my-action  # assuming this is your composite action location
        with:
          test_results: ${{ needs.test.result == 'success' && 'All tests have passed!' || 'There are failures.' }}
          run_id: ${{ github.run_id }}
          run_number: ${{ github.run_number }}
          status: ${{ needs.test.result == 'success' && 'success' || 'failure' }}
          source_repo: ${{ github.repository }}
          failed_tests: ${{ needs.test.result == 'success' && 'N/A' || env.FAILED_TESTS }}
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL_CI_TESTS_ALERTS }}
    
